// TODO: These values are not accurate; whoever works on this project
// will need to update both the ARABIC_KEYBOARD and QWERTY_TO_ARABIC_KEY
// values to make sure they reflect the correct keyboard layout.

/** Arabic keyboard, list of rows. Each row is a list of keys */
export const ARABIC_KEYBOARD = [
    [
        { letter: 'ذ' },
        { letter: '١' },
        { letter: '٢' },
        { letter: '٣' },
        { letter: '٤' },
        { letter: '٥' },
        { letter: '٦' },
        { letter: '٧' },
        { letter: '٨' },
        { letter: '٩' },
        { letter: '٠' },
        { letter: '~' },
        { letter: '!' },
    ],
    [
        { letter: 'ض' },
        { letter: 'ص' },
        { letter: 'ث' },
        { letter: 'ق' },
        { letter: 'قف' },
        { letter: 'غ' },
        { letter: 'ع' },
        { letter: 'ه' },
        { letter: 'خ' },
        { letter: 'خ' },
        { letter: 'ح' },
        { letter: 'ج' },
        { letter: 'د' },
    ],
    [
        { letter: 'ش' },
        { letter: 'س' },
        { letter: 'ي' },
        { letter: 'ب' },
        { letter: 'ل' },
        { letter: 'ا' },
        { letter: 'ت' },
        { letter: 'ن' },
        { letter: 'م' },
        { letter: 'ك' },
        { letter: 'ظ' },
    ],
    [
        { letter: 'ئ' },
        { letter: 'ء' },
        { letter: 'ؤ' },
        { letter: 'ر' },
        { letter: 'لا' },
        { letter: 'ى' },
        { letter: 'ة' },
        { letter: 'و' },
        { letter: 'ز' },
        { letter: 'ظ' },
    ],
    [
        { letter: ' ' }
    ]
];

/** Maps QWERTY key values to the corresponding Arabic letter. */
export const QWERTY_TO_ARABIC = {
    '`':'ذ',
    '1':'١',
    '2': '٢',
    '3': '٣',
    '4': '٤',
    '5': '٥',
    '6': '٦',
    '7': '٧',
    '8': '٨',
    '9':  '٩',
    '0':  '٠',
    '-':  '~',
    '=': '!',
    'q': 'ض',
    'w': 'ص',
    'e': 'ث',
    'r': 'ق',
    't': 'قف',
    'y': 'غ',
    'u': 'ع',
    'i': 'ه',
    'o': 'خ',
    'p': 'خ',
    '[': 'ح',
    ']': 'ج',
    '\\': 'د',
    'a': 'ش',
    's': 'س',
    'd': 'ي',
    'f': 'ب',
    'g': 'ل',
    'h': 'ا',
    'j': 'ت',
    'k': 'ن',
    'l': 'م',
    ';': 'ك',
    '\'': 'ظ',
    'z': 'ئ',
    'x': 'ء',
    'c': 'ؤ',
    'v': 'ر',
    'b': 'لا',
    'n': 'ى',
    'm': 'ة',
    ',': 'و',
    '.': 'ز',
    '/': 'ظ',
    ' ': ' ',
};